service: workshop${self:custom.name}

custom:
  name: 'jon'
  email: 'jon.barber@acm.org'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get
